import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:prep_quest/core/theme/app_theme.dart';
import 'package:prep_quest/core/widgets/primary_button.dart';

import '../../helpers/golden_test_utils.dart';

/// Golden tests for the [PrimaryButton] widget.
///
/// Captures every variant × size combination in light + dark themes.
/// Goldens can be regenerated by running:
///
///     UPDATE_GOLDENS=true flutter test test/golden/buttons/...
void main() {
  // Constants used across all captures. Pulled out so the golden
  // filename and the widget under test stay in sync.
  const String label = 'Get Started';
  const double buttonWidth = 280;

  Widget wrap(Widget child) => Center(
        child: SizedBox(
          width: buttonWidth,
          child: child,
        ),
      );

  // ---------------------------------------------------------------------------
  // Filled variant — the canonical primary CTA across light and dark themes
  // ---------------------------------------------------------------------------
  group('PrimaryButton · filled', () {
    for (final PrimaryButtonSize size in PrimaryButtonSize.values) {
      testWidgets('filled · $size · light+dark', (WidgetTester tester) async {
        tester.view.physicalSize = const Size(360, 200);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        await captureGoldenPair(
          tester,
          'buttons/primary_button_filled_${size.name}',
          builder: (BuildContext context, ThemeMode mode) => wrap(
            PrimaryButton(
              text: label,
              onPressed: () {},
              variant: PrimaryButtonVariant.filled,
              size: size,
            ),
          ),
        );
      });
    }
  });

  // ---------------------------------------------------------------------------
  // Gradient variant — used for hero CTAs
  // ---------------------------------------------------------------------------
  group('PrimaryButton · gradient', () {
    for (final PrimaryButtonSize size in PrimaryButtonSize.values) {
      testWidgets('gradient · $size · light+dark', (WidgetTester tester) async {
        tester.view.physicalSize = const Size(360, 200);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        await captureGoldenPair(
          tester,
          'buttons/primary_button_gradient_${size.name}',
          builder: (BuildContext context, ThemeMode mode) => wrap(
            PrimaryButton(
              text: label,
              onPressed: () {},
              variant: PrimaryButtonVariant.gradient,
              size: size,
            ),
          ),
        );
      });
    }
  });

  // ---------------------------------------------------------------------------
  // Outlined variant — secondary emphasis
  // ---------------------------------------------------------------------------
  group('PrimaryButton · outlined', () {
    testWidgets('outlined · medium · light+dark', (
      WidgetTester tester,
    ) async {
      tester.view.physicalSize = const Size(360, 200);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);

      await captureGoldenPair(
        tester,
        'buttons/primary_button_outlined_medium',
        builder: (BuildContext context, ThemeMode mode) => wrap(
          PrimaryButton(
            text: label,
            onPressed: () {},
            variant: PrimaryButtonVariant.outlined,
            size: PrimaryButtonSize.medium,
          ),
        ),
      );
    });
  });

  // ---------------------------------------------------------------------------
  // Tonal variant
  // ---------------------------------------------------------------------------
  group('PrimaryButton · tonal', () {
    testWidgets('tonal · medium · light+dark', (WidgetTester tester) async {
      tester.view.physicalSize = const Size(360, 200);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);

      await captureGoldenPair(
        tester,
        'buttons/primary_button_tonal_medium',
        builder: (BuildContext context, ThemeMode mode) => wrap(
          PrimaryButton(
            text: label,
            onPressed: () {},
            variant: PrimaryButtonVariant.tonal,
            size: PrimaryButtonSize.medium,
          ),
        ),
      );
    });
  });

  // ---------------------------------------------------------------------------
  // States: loading, disabled
  // ---------------------------------------------------------------------------
  group('PrimaryButton · states', () {
    testWidgets('loading · medium · light+dark', (WidgetTester tester) async {
      // Skipped: indeterminate progress spinners rotate continuously and
      // produce non-deterministic pixels across runs. We keep the test
      // as a smoke check that the loading state mounts without throwing.
      tester.view.physicalSize = const Size(360, 200);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);

      for (final ThemeMode mode in ThemeMode.values) {
        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.light(),
            darkTheme: AppTheme.dark(),
            themeMode: mode,
            home: Scaffold(
              body: wrap(
                PrimaryButton(
                  text: label,
                  onPressed: () {},
                  size: PrimaryButtonSize.medium,
                  isLoading: true,
                ),
              ),
            ),
          ),
        );
        await tester.pump(const Duration(milliseconds: 50));
        expect(tester.takeException(), isNull);
      }
    });

    testWidgets('disabled · medium · light+dark', (WidgetTester tester) async {
      tester.view.physicalSize = const Size(360, 200);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);

      await captureGoldenPair(
        tester,
        'buttons/primary_button_disabled_medium',
        builder: (BuildContext context, ThemeMode mode) => wrap(
          PrimaryButton(
            text: label,
            onPressed: () {},
            size: PrimaryButtonSize.medium,
            isEnabled: false,
          ),
        ),
      );
    });

    testWidgets('with icon · medium · light+dark', (
      WidgetTester tester,
    ) async {
      tester.view.physicalSize = const Size(360, 200);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);

      await captureGoldenPair(
        tester,
        'buttons/primary_button_with_icon_medium',
        builder: (BuildContext context, ThemeMode mode) => wrap(
          PrimaryButton(
            text: label,
            onPressed: () {},
            size: PrimaryButtonSize.medium,
            icon: Icons.rocket_launch_rounded,
          ),
        ),
      );
    });
  });
}