import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:prep_quest/core/widgets/secondary_button.dart';

import '../../helpers/golden_test_utils.dart';

/// Golden tests for the [SecondaryButton] widget.
///
/// Captures every variant × size combination in light + dark themes.
/// Goldens can be regenerated by running:
///
///     UPDATE_GOLDENS=true flutter test test/golden/buttons/...
void main() {
  const String label = 'Maybe Later';
  const double buttonWidth = 280;

  Widget wrap(Widget child) => Center(
        child: SizedBox(
          width: buttonWidth,
          child: child,
        ),
      );

  // ---------------------------------------------------------------------------
  // Outlined variant — the canonical secondary CTA
  // ---------------------------------------------------------------------------
  group('SecondaryButton · outlined', () {
    for (final SecondaryButtonSize size in SecondaryButtonSize.values) {
      testWidgets('outlined · $size · light+dark', (
        WidgetTester tester,
      ) async {
        tester.view.physicalSize = const Size(360, 200);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        await captureGoldenPair(
          tester,
          'buttons/secondary_button_outlined_${size.name}',
          builder: (BuildContext context, ThemeMode mode) => wrap(
            SecondaryButton(
              text: label,
              onPressed: () {},
              variant: SecondaryButtonVariant.outlined,
              size: size,
            ),
          ),
        );
      });
    }
  });

  // ---------------------------------------------------------------------------
  // Tonal variant
  // ---------------------------------------------------------------------------
  group('SecondaryButton · tonal', () {
    for (final SecondaryButtonSize size in SecondaryButtonSize.values) {
      testWidgets('tonal · $size · light+dark', (WidgetTester tester) async {
        tester.view.physicalSize = const Size(360, 200);
        tester.view.devicePixelRatio = 1.0;
        addTearDown(tester.view.resetPhysicalSize);
        addTearDown(tester.view.resetDevicePixelRatio);

        await captureGoldenPair(
          tester,
          'buttons/secondary_button_tonal_${size.name}',
          builder: (BuildContext context, ThemeMode mode) => wrap(
            SecondaryButton(
              text: label,
              onPressed: () {},
              variant: SecondaryButtonVariant.tonal,
              size: size,
            ),
          ),
        );
      });
    }
  });

  // ---------------------------------------------------------------------------
  // Text variant
  // ---------------------------------------------------------------------------
  group('SecondaryButton · text', () {
    testWidgets('text · medium · light+dark', (WidgetTester tester) async {
      tester.view.physicalSize = const Size(360, 200);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);

      await captureGoldenPair(
        tester,
        'buttons/secondary_button_text_medium',
        builder: (BuildContext context, ThemeMode mode) => wrap(
          SecondaryButton(
            text: label,
            onPressed: () {},
            variant: SecondaryButtonVariant.text,
            size: SecondaryButtonSize.medium,
          ),
        ),
      );
    });
  });

  // ---------------------------------------------------------------------------
  // Glass variant
  // ---------------------------------------------------------------------------
  group('SecondaryButton · glass', () {
    testWidgets('glass · medium · light+dark', (WidgetTester tester) async {
      tester.view.physicalSize = const Size(360, 200);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);

      await captureGoldenPair(
        tester,
        'buttons/secondary_button_glass_medium',
        builder: (BuildContext context, ThemeMode mode) => wrap(
          SecondaryButton(
            text: label,
            onPressed: () {},
            variant: SecondaryButtonVariant.glass,
            size: SecondaryButtonSize.medium,
          ),
        ),
      );
    });
  });

  // ---------------------------------------------------------------------------
  // States: loading, disabled
  // ---------------------------------------------------------------------------
  group('SecondaryButton · states', () {
    testWidgets('loading · medium · light+dark', (WidgetTester tester) async {
      tester.view.physicalSize = const Size(360, 200);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);

      await captureGoldenPair(
        tester,
        'buttons/secondary_button_loading_medium',
        builder: (BuildContext context, ThemeMode mode) => wrap(
          SecondaryButton(
            text: label,
            onPressed: () {},
            size: SecondaryButtonSize.medium,
            isLoading: true,
          ),
        ),
      );
    });

    testWidgets('disabled · medium · light+dark', (WidgetTester tester) async {
      tester.view.physicalSize = const Size(360, 200);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);

      await captureGoldenPair(
        tester,
        'buttons/secondary_button_disabled_medium',
        builder: (BuildContext context, ThemeMode mode) => wrap(
          SecondaryButton(
            text: label,
            onPressed: () {},
            size: SecondaryButtonSize.medium,
            isEnabled: false,
          ),
        ),
      );
    });

    testWidgets('with icon · medium · light+dark', (
      WidgetTester tester,
    ) async {
      tester.view.physicalSize = const Size(360, 200);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.resetPhysicalSize);
      addTearDown(tester.view.resetDevicePixelRatio);

      await captureGoldenPair(
        tester,
        'buttons/secondary_button_with_icon_medium',
        builder: (BuildContext context, ThemeMode mode) => wrap(
          SecondaryButton(
            text: label,
            onPressed: () {},
            size: SecondaryButtonSize.medium,
            icon: Icons.arrow_back_rounded,
          ),
        ),
      );
    });
  });
}