import 'package:flutter/foundation.dart';

/// Sign of a coin transaction relative to the user's balance.
///
/// [earn], [bonus], [reward], [restore] credit coins (positive delta).
/// [spend], [refund] debit or restore coins depending on context.
enum CoinTransactionType {
  earn,
  spend,
  refund,
  bonus,
  reward,
  purchase,
  restore;

  /// Maps the enum to a stable wire string. Used by Firestore
  /// serialization so consumers can decode the value without
  /// depending on the Dart enum ordering.
  String get id {
    switch (this) {
      case CoinTransactionType.earn:
        return 'earn';
      case CoinTransactionType.spend:
        return 'spend';
      case CoinTransactionType.refund:
        return 'refund';
      case CoinTransactionType.bonus:
        return 'bonus';
      case CoinTransactionType.reward:
        return 'reward';
      case CoinTransactionType.purchase:
        return 'purchase';
      case CoinTransactionType.restore:
        return 'restore';
    }
  }
}

/// Source namespace for a coin transaction. Used as part of the
/// `{source}:{sourceId}` dedup key on the ledger.
enum CoinTransactionSource {
  quiz,
  mission,
  daily,
  chest,
  streak,
  lesson,
  level,
  levelReward,
  boss,
  achievement,
  badge,
  xpMilestone,
  specialEvent,
  purchase,
  refund;

  String get id {
    switch (this) {
      case CoinTransactionSource.quiz:
        return 'quiz';
      case CoinTransactionSource.mission:
        return 'mission';
      case CoinTransactionSource.daily:
        return 'daily';
      case CoinTransactionSource.chest:
        return 'chest';
      case CoinTransactionSource.streak:
        return 'streak';
      case CoinTransactionSource.lesson:
        return 'lesson';
      case CoinTransactionSource.level:
        return 'level';
      case CoinTransactionSource.levelReward:
        return 'levelReward';
      case CoinTransactionSource.boss:
        return 'boss';
      case CoinTransactionSource.achievement:
        return 'achievement';
      case CoinTransactionSource.badge:
        return 'badge';
      case CoinTransactionSource.xpMilestone:
        return 'xpMilestone';
      case CoinTransactionSource.specialEvent:
        return 'specialEvent';
      case CoinTransactionSource.purchase:
        return 'purchase';
      case CoinTransactionSource.refund:
        return 'refund';
    }
  }
}

/// One persisted coin ledger entry — one document under
/// `users/{uid}/coin_ledger/{txId}`. The ledger is append-only: a
/// single grant / spend / refund produces exactly one
/// [CoinTransactionEntity], regardless of how many times the same
/// `{source}:{sourceId}` key is re-submitted (replays fail with a
/// [DuplicateRewardFailure]).
@immutable
class CoinTransactionEntity {
  const CoinTransactionEntity({
    required this.id,
    required this.uid,
    required this.type,
    required this.source,
    required this.sourceId,
    required this.amount,
    required this.balanceAfter,
    required this.createdAt,
    this.reason,
    this.metadata = const <String, dynamic>{},
  });

  /// Firestore document id (auto-generated by `.add()`).
  final String id;

  /// Owning user id — used by realtime listeners and offline replay.
  final String uid;

  /// Sign / category of the transaction.
  final CoinTransactionType type;

  /// Source namespace — paired with [sourceId] to form the dedup
  /// [sourceKey].
  final CoinTransactionSource source;

  /// Stable id within the source (e.g. quiz `sessionId`, mission
  /// `missionId`, level-up `level@queuedAt`).
  final String sourceId;

  /// Magnitude in coins (always positive; sign carried by [type]).
  final int amount;

  /// Balance after this transaction was applied. Persisted at
  /// write-time so the history screen never needs to recompute.
  final int balanceAfter;

  /// Optional human-readable label for the celebration UI.
  final String? reason;

  /// Free-form context (e.g. `quizId`, `correctCount`, `chestRarity`).
  final Map<String, dynamic> metadata;

  /// Wall-clock UTC timestamp of the transaction.
  final DateTime createdAt;

  /// Composite dedup key. Format: `"$source:$sourceId"` (e.g.
  /// `"quiz:abc-123"`, `"levelReward:5@2024-05-01T10:30:00Z"`).
  String get sourceKey => '${source.id}:$sourceId';

  /// Signed delta derived from [type]. `spend` debits, everything
  /// else credits. Used by [CoinService] to compute `balanceAfter`.
  int get signedDelta {
    switch (type) {
      case CoinTransactionType.spend:
        return -amount;
      case CoinTransactionType.earn:
      case CoinTransactionType.refund:
      case CoinTransactionType.bonus:
      case CoinTransactionType.reward:
      case CoinTransactionType.purchase:
      case CoinTransactionType.restore:
        return amount;
    }
  }

  CoinTransactionEntity copyWith({
    String? id,
    String? uid,
    CoinTransactionType? type,
    CoinTransactionSource? source,
    String? sourceId,
    int? amount,
    int? balanceAfter,
    DateTime? createdAt,
    String? reason,
    Map<String, dynamic>? metadata,
  }) {
    return CoinTransactionEntity(
      id: id ?? this.id,
      uid: uid ?? this.uid,
      type: type ?? this.type,
      source: source ?? this.source,
      sourceId: sourceId ?? this.sourceId,
      amount: amount ?? this.amount,
      balanceAfter: balanceAfter ?? this.balanceAfter,
      createdAt: createdAt ?? this.createdAt,
      reason: reason ?? this.reason,
      metadata: metadata ?? this.metadata,
    );
  }

  /// Decodes a Firestore-shaped map. Unknown keys are ignored; missing
  /// keys fall back to safe defaults so partial documents from older
  /// schemas still hydrate.
  factory CoinTransactionEntity.fromMap(Map<String, dynamic> map) {
    final CoinTransactionType parsedType =
        _decodeType(map['type'] as String?) ?? CoinTransactionType.earn;
    final CoinTransactionSource parsedSource =
        _decodeSource(map['source'] as String?) ?? CoinTransactionSource.quiz;
    return CoinTransactionEntity(
      id: (map['id'] as String?) ??
          (map['txId'] as String?) ??
          '',
      uid: (map['uid'] as String?) ?? '',
      type: parsedType,
      source: parsedSource,
      sourceId: (map['sourceId'] as String?) ?? '',
      amount: (map['amount'] as num?)?.toInt() ?? 0,
      balanceAfter: (map['balanceAfter'] as num?)?.toInt() ?? 0,
      reason: map['reason'] as String?,
      metadata: (map['metadata'] as Map<String, dynamic>?) ??
          const <String, dynamic>{},
      createdAt:
          DateTime.tryParse(map['createdAt'] as String? ?? '')?.toLocal() ??
              DateTime.now(),
    );
  }

  /// Encodes the entity to the canonical Firestore shape. The
  /// `id` and `uid` are emitted alongside the rest so the document is
  /// self-describing when read back via `fromMap`.
  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'id': id,
      'uid': uid,
      'type': type.id,
      'source': source.id,
      'sourceId': sourceId,
      'sourceKey': sourceKey,
      'amount': amount,
      'balanceAfter': balanceAfter,
      'reason': reason,
      'metadata': metadata,
      'createdAt': createdAt.toUtc().toIso8601String(),
    };
  }

  static CoinTransactionType? _decodeType(String? value) {
    if (value == null) return null;
    for (final CoinTransactionType t in CoinTransactionType.values) {
      if (t.id == value) return t;
    }
    return null;
  }

  static CoinTransactionSource? _decodeSource(String? value) {
    if (value == null) return null;
    for (final CoinTransactionSource s in CoinTransactionSource.values) {
      if (s.id == value) return s;
    }
    return null;
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! CoinTransactionEntity) return false;
    return other.id == id &&
        other.uid == uid &&
        other.type == type &&
        other.source == source &&
        other.sourceId == sourceId &&
        other.amount == amount &&
        other.balanceAfter == balanceAfter &&
        other.reason == reason &&
        other.createdAt == createdAt &&
        _mapEquals(other.metadata, metadata);
  }

  @override
  int get hashCode => Object.hash(
        id,
        uid,
        type,
        source,
        sourceId,
        amount,
        balanceAfter,
        reason,
        createdAt,
        Object.hashAllUnordered(
          metadata.entries.map((MapEntry<String, dynamic> e) => Object.hash(e.key, e.value)),
        ),
      );

  static bool _mapEquals(
    Map<String, dynamic> a,
    Map<String, dynamic> b,
  ) {
    if (identical(a, b)) return true;
    if (a.length != b.length) return false;
    for (final MapEntry<String, dynamic> entry in a.entries) {
      if (!b.containsKey(entry.key) || b[entry.key] != entry.value) {
        return false;
      }
    }
    return true;
  }
}