// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNwiqSECIxfKzsstJlbP4fc_Iuig20NnA',
    appId: '1:1098456291599:web:451c374949faf9a43f067a',
    messagingSenderId: '1098456291599',
    projectId: 'prep-quest-f751e',
    authDomain: 'prep-quest-f751e.firebaseapp.com',
    storageBucket: 'prep-quest-f751e.firebasestorage.app',
    measurementId: 'G-ND363J8KDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnSX4qZFNTanhZ-XxzQgbRhiz_nqgBu3E',
    appId: '1:1098456291599:android:88e0345a057e90a03f067a',
    messagingSenderId: '1098456291599',
    projectId: 'prep-quest-f751e',
    storageBucket: 'prep-quest-f751e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHzT8EXHc0wW0gFrWzr8ffs-9QskIXgXo',
    appId: '1:1098456291599:ios:fbc1d6c3260e2aa33f067a',
    messagingSenderId: '1098456291599',
    projectId: 'prep-quest-f751e',
    storageBucket: 'prep-quest-f751e.firebasestorage.app',
    iosBundleId: 'com.example.prep_quest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHzT8EXHc0wW0gFrWzr8ffs-9QskIXgXo',
    appId: '1:1098456291599:ios:fbc1d6c3260e2aa33f067a',
    messagingSenderId: '1098456291599',
    projectId: 'prep-quest-f751e',
    storageBucket: 'prep-quest-f751e.firebasestorage.app',
    iosBundleId: 'com.example.prep_quest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNwiqSECIxfKzsstJlbP4fc_Iuig20NnA',
    appId: '1:1098456291599:web:a6469f6f74bbdce13f067a',
    messagingSenderId: '1098456291599',
    projectId: 'prep-quest-f751e',
    authDomain: 'prep-quest-f751e.firebaseapp.com',
    storageBucket: 'prep-quest-f751e.firebasestorage.app',
    measurementId: 'G-CWVKKMRF7M',
  );
}
