import 'package:flutter/material.dart';

import '../../../../../../../../core/constants/app_spacing.dart';
import '../../../providers/widget_builder_provider.dart';
import 'playground_control_dropdown.dart';

class PlaygroundLegendControls extends StatelessWidget {
  const PlaygroundLegendControls({super.key, required this.provider});

  final WidgetBuilderProvider provider;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: <Widget>[
        const SizedBox(height: AppSpacing.xl),
        Text('Map Legend Options', style: theme.textTheme.titleMedium),
        const SizedBox(height: AppSpacing.sm),
        Text(
          'The Playground Legend renders every node, building, reward, and '
          'path swatch generated by the production defaults.',
          style: theme.textTheme.bodySmall,
        ),
        const SizedBox(height: AppSpacing.md),
        TextFormField(
          initialValue: provider.playgroundLegendTitle,
          decoration: const InputDecoration(labelText: 'Legend title'),
          onChanged: (value) => provider.playgroundLegendTitle = value,
        ),
        const SizedBox(height: AppSpacing.md),
        PlaygroundControlDropdown(
          label: 'Theme Preview',
          value: provider.playgroundLegendBrightness,
          values: const <String, String>{
            'lightOnly': 'Light',
            'darkOnly': 'Dark',
            'sideBySide': 'Side by Side',
          },
          onChanged: (value) => provider.playgroundLegendBrightness = value,
        ),
      ],
    );
  }
}
