import 'package:firebase_auth/firebase_auth.dart' as firebase_auth;
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

import '../../firebase_options.dart';
import '../../features/offline/data/hive/hive_adapters.dart';
import '../cache/hive_manager.dart';
import '../constants/api_endpoints.dart';

/// Single source for environment-aware application configuration.
///
/// Anything that varies per build flavor / deployment should live here:
/// api base URLs, feature flags, default locale, asset roots, etc. Feature
/// code should read values from [AppConfig.instance] rather than duplicating
/// environment checks.
class AppConfig {
  AppConfig._({
    required this.environment,
    required this.isProduction,
    required this.defaultLocale,
    required this.themeMode,
  });

  /// Fully-initialized application configuration.
  ///
  /// Should not be read before [bootstrap] has been awaited.
  static AppConfig get instance {
    final AppConfig? config = _instance;
    if (config == null) {
      throw StateError(
        'AppConfig accessed before bootstrap() completed. '
        'Await bootstrap() in your entry point.',
      );
    }
    return config;
  }

  static AppConfig? _instance;

  /// The name of the current environment (`dev`, `staging`, `prod`, ...).
  final String environment;

  /// `true` when running in production builds. Useful for hiding debug UI
  /// such as the checked-mode banner or debug overlays.
  final bool isProduction;

  /// Locale used when the user has not picked a preference yet.
  final Locale defaultLocale;

  /// Initial [ThemeMode]. The user can override this at runtime through
  /// the shared theme provider under `core/providers/theme_provider.dart`.
  final ThemeMode themeMode;

  /// Performs one-time environment detection and stores the resulting
  /// configuration so the rest of the application can read it.
  ///
  /// Heavy async work (Firebase init, Hive box opening, asset precaching)
  /// is triggered from here, **not** from `main.dart`, so that test
  /// harnesses can substitute their own [bootstrap] implementation.
  static Future<void> bootstrap() async {
    // Environment resolution order:
    //   1. Compile-time `--dart-define=APP_ENV=...` value.
    //   2. Fallback `dev` so local runs never crash.
    const String environment = String.fromEnvironment(
      'APP_ENV',
      defaultValue: 'dev',
    );

    final bool isProduction = environment == 'prod';
    final ThemeMode themeMode = isProduction
        ? ThemeMode.system
        : ThemeMode.system;

    _instance = AppConfig._(
      environment: environment,
      isProduction: isProduction,
      defaultLocale: const Locale('en'),
      themeMode: themeMode,
    );

    // Initialise Firebase Auth + Firestore before any feature service
    // touches them. Without this call `FirebaseConfig.isPlatformConfigured`
    // returns false and every provider falls back to its mock data
    // source — that is why the "Continue with Google" button appeared
    // to do nothing in earlier builds (the mock completed silently
    // instead of opening the Google account picker). `DefaultFirebase
    // Options.currentPlatform` is generated by the FlutterFire CLI and
    // carries the apiKey / appId / projectId for the active target.
    try {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    } catch (error, stackTrace) {
      // Firebase init can fail on Linux / unsupported platforms. We
      // surface the failure to the debug console but do NOT crash the
      // app — features that need Firebase already guard every access
      // through `FirebaseConfig.isPlatformConfigured` and degrade to
      // mock sources so the rest of the UI still works.
      if (kDebugMode) {
        debugPrint(
          '[AppConfig] Firebase.initializeApp failed: $error\n'
          '$stackTrace',
        );
      }
    }

    // Clear any persisted Firebase Auth / Google sign-in session that
    // was cached on disk from a previous app run. Without this step the
    // platform layer restores the previous Google account the moment the
    // app boots and [FirebaseAuth.instance.currentUser] returns a
    // non-null user before the user has even seen the welcome screen,
    // which causes the splash router to skip /welcome and land directly
    // on /playground while the Google account picker opens silently in
    // the background. Forcing an explicit sign-out on every boot
    // guarantees the welcome screen is the first thing the user sees
    // and every sign-in requires an explicit tap on the Google button.
    await _clearPersistedAuthSession();

    await HiveManager.instance.initialize(
      registrars: <AdapterRegistrar>[registerOfflineAdapters],
    );

    if (kDebugMode) {
      debugPrint(
        '[AppConfig] env=${_instance!.environment} '
        'isProduction=${_instance!.isProduction} '
        'apiBase=${ApiEndpoints.baseUrl} '
        'hive=${HiveManager.instance.isInitialized}',
      );
    }
  }

  /// Forces a clean auth slate on every app launch.
  ///
  /// Firebase Auth persists the user's session to disk and rehydrates it
  /// on the next app run, and the Google Sign-In plugin keeps its own
  /// silent-account state on top of that. The combination makes the
  /// app behave as if the user were already signed in — the welcome
  /// screen never renders, the router jumps straight to /playground,
  /// and the Google account picker may pop up without any tap on the
  /// sign-in button. Both layers need to be cleared so the user has to
  /// explicitly choose to sign in again.
  ///
  /// Failures are intentionally swallowed: if either call throws (e.g.
  /// on a platform where Google Sign-In is unavailable) we still want to
  /// hand control to the auth controller so it can present an
  /// unauthenticated welcome screen rather than a half-cleared state.
  static Future<void> _clearPersistedAuthSession() async {
    try {
      await GoogleSignIn().signOut();
    } on Object catch (error, stackTrace) {
      if (kDebugMode) {
        debugPrint(
          '[AppConfig] GoogleSignIn.signOut during boot failed: $error\n'
          '$stackTrace',
        );
      }
    }
    try {
      await firebase_auth.FirebaseAuth.instance.signOut();
    } on Object catch (error, stackTrace) {
      if (kDebugMode) {
        debugPrint(
          '[AppConfig] FirebaseAuth.signOut during boot failed: $error\n'
          '$stackTrace',
        );
      }
    }
  }
}